langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: a5PCdd47XT0h3AAdIeBi4MEBww0+tEGUYYp5zHNc3QG9GSdJfRs5bxIRe5bDTLUu29T6JvmzJpLSMI9XE0jvAU6m5n3FmNabmz63AhcBszzqf4rDK15YLG0HpCAJenXVj9cdoAqMo6+fwS5mj6SFlgf2s6MyZS5HxyH4mTUd6/+5cxVzqcYu7Z1ApjcoZmfVyzECS/e38JSxnKH/fkr9yziGFeOmcv1zxCHnPL14MGd9Fp9EmiL31/JKFyxGE4E47CdLZvfYy3b5zBGKdVbl4AVMKfwrtmj69fW0CQogg0NRQ0CqqS2qGND6dHk4grCQfgZHGj6Q+FJsBkeSYCBBTrlgP2thGyUi36a4jV4x1Pj+rTUb/cUbYiwNJSp/VpHxI8diFJshKSqbcHNdGK1lCrWxHGc3wpwU2upSjxjPjNQ3wHuyqvWyUsP41F4GVNyy7C5W7KYv7Jno73NIF02ngWyihF+zlwinRvfnmhMLoLyQni+ALrXHG4JCohB/rHifpXjB2zkudmliy0qMH/J6CeTXeDuVTZvzsDwDKuegpVvQ6eq1f5FjTcZNTPt7Xnko3dMikTDGSNYX01GucfG5a/zMObVBEw+T35OrduuIYbpkGnP0a6Sdz5r3kKw0tXcxlbj5/KThvUVl4bOE4eICDGMTt4dpyzQCODFclzqZWWU=
  app: weather-bop
  run: rails db:migrate
env:
  global:
    secure: HfsUBpcYHlGXjdR+hbP60Vjc0RrfbGKTPysUvxnEvQmj00DR/ClciMsWPWaCNBKAoLcqlgnklFsGDNK3T9Z4BGijgBO+18WB2E0H85Q7reIST5b7ZkYX5Xhlwwpf6VvDbUE5os2kLB+9cwRFIvfqfJqKo0WMeqH2iocdDsaDN7Q9M8KsH/K7xtVGZ3wJRUyHyo2IWv+soOWlZYn0HSKLtH64F4IhH2U7djKdyCGla9rQ7cUVvpnn2C5QdVC5HsE5kKWh6hGTa63PnZSVxiN7B0CbhH3bKp0Asx+G5DwGv7+PlZfrfaU7sVh8IWUAtoCWyoUuo9Q4IztrTzxV8Kp/guKosgFitmPnQJMCeeBLPXe1gGtidCwlfI9/re1Ur51+ev57w6nKj6nKU+uHg6ytTRqHqy1ZM0lt95KUXZsbcO1ezahg50n1DNrj/0ot648yjM9R5NpSWKBJvXxwvRPjzpFGEdrWMw3u9ap667lEUBqTV8HRgx5ClDTsmBjtKV+zsYlnRp+b261PKLrDsvWVKgyLT0FO5ykm6bAd8O8IRHMWxBuoKh/khT3KQtJ9k6KeIfwshJueMU38qYjFhwihUYcYLyHfx2JEF3hwYeDDkfPl0CT1JSKpYZ+vjZupAPSizzKd5v0/psZHUXUkVFnBnGo8151GIkF0kJQVXvg7nj4=
